# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5Y1YKNjpqw9aiqXUGIff7GGiAlGMQLM
"""

name=(input("Enter the name:"))
Marks=float (input ("Enter the Marks:"))
if Marks>=45:
   print ("PASS")
else:
   print("FAIL")

my_var=100
print(f"Value:{my_var}, Type:{type(my_var)}")

my_var="Now I'm string"
print(f"Value:{my_var}, Type:{type(my_var)}")

a=5
print(f"Initial Value of a: {a}, Address: {id(a)}")
a=a+1
print(id(a))

list_a=[10,20,30]
list_b=list_a   #both variables point to same list

list_b.append(40)
print(f"list_b:{list_b}")
print(f"list_a:{list_a}")

print(f"Are list_a and list_b same?{list_a is list_b}")

list_a=[10,20,30]
list_c= list_a.copy()   #creates a shallow copy
list_c.append(50)
print(f"Modified List: {list_c}")
print(f"Original List: {list_a}")

print(f"Are list_a and _list_c same? {list_a is list_c}")

#Type casting/Conversion
num_int=20
num_float=5.5
result= num_int + num_float   #implicit conversion
print(f"Value: {result}, Type: {type(result)}")

#Explicit conversion
str_num="123"
casted_num=int(str_num)

print(f"Value: {casted_int}, Type:{type(casted_int)}")

#converting list into set to remove duplicates

number_list= [1,2,2,3,4,5,5,6]
unique_numbers=set(number_list)
print(f"Original list: {number_list}")
print(f"Unique set: {unique_numbers}")

#tuple into list
fruits= ("apple","cherry","orange")

l_fruits=list(fruits)
l_fruits[1]="banana"
fruits= tuple(l_fruits)
print(fruits)

#Dictionary

hyperparameters={
    "learning_rate":0.001,
    "batch_size":32,
    "optimizer":"Adam",
    "epochs":10,
    "early_stopping":True
}
print("Learning rate:",hyperparameters["learning_rate"])
print("Batch size:",hyperparameters["batch_size"])
print("Optimizer:",hyperparameters["optimizer"])
print("Epochs:",hyperparameters["epochs"])
print("Early stopping:",hyperparameters["early_stopping"])

#updating
hyperparameters["learning_rate"]=0.005
print("\nUpdated Hyperparameters:",hyperparameters)

roles=["admin","user","user","editor","admin","user","viewer"]
print("Total user accounts:",len(roles))

unique_roles=set(roles)
print("Unique roles:",unique_roles)

print("Count of unique roles:", len(unique_roles))

#Check prime numbers
number_to_check=7
is_prime=True

if number_to_check<=1:
  is_prime=False
else:
  for i in range(2,int(number_to_check**0.5)+1):
    if number_to_check%i==0:
      is_prime=False
      break

if is_prime:
  print(f"{number_to_check} is a prime number.")
else:
  print(f"{number_to_check} is not a prime number.")

#prime number
num=int(input("Enter a number:"))

if num<=1:
  print(f"{num} is not a prime number.")
else:
  for i in range(2,int(num**0.5)+1):
    if num%i==0:
      print(f"{num} is not a prime number")
      break
  else:
    print(f"{num} is a prime number")

name=input("Enter student name:")
marks=float(input("Enter marks obtained:"))

if marks>=30:
  status="Pass"
else:
  status="Fail"

print("\n"+"="*30)
print("        Result Card   ")
print("="*30)
print(f"Student Name: {name}")
print(f"Marks Obtained: {marks}/100")
print(f"Status: {status}")
print("="*30)

x=42
y=x
print(f"id(x):{id(x)}")
print(f"id(y):{id(y)}")

my_int=-10
my_float=5.345
my_complex=2+3j

print(f"Int:{my_int} ({type(my_int)})")
print(f"Float:{my_float} ({type(my_float)})")
print(f"Complex:{my_complex.real} , Imaginary part:{my_complex.imag}")
#

a=[1,2,3]
b=a
c=[1,2,3]

print(a is b)
print(a==c)
print(a is c)

